const comedyMap = {
  witnesses: 'these dudes I know',
  allegedly: 'kinda probably',
  'new study': 'tumblr post',
  rebuild: 'avenge',
  space: 'spaaaace',
  'google glass': 'virtual boy',
  smartphone: 'pokedex',
  electric: 'atomic',
  senator: 'elf lord',
  'car ': 'cat ',
  election: 'eating contest',
  'congressional leaders': 'river spirits',
  'homeland security': 'homestar runner',
  'could not be reached for comment': 'is guilty and everyone knows it',
  debate: 'dance off',
  'self driving': 'uncontrollably swerving',
  poll: 'psychic reading',
  candidate: 'airbender',
  drone: 'dog',
  'vows to': 'probably won\'t',
  'at large': 'very large',
  successfully: 'suddenly',
  expands: 'physically expands',
  'first-degree': 'friggin awful',
  'an unknown number': 'like hundreds',
  'front runner': 'blade runner',
  global: 'spherical',
  years: 'minutes',
  'this year': 'on Tuesday',
  minutes: 'years',
  'no indication': 'lots of signs',
  'urged restraint by': 'drunkenly egged on',
  horsepower: 'tons of horsemeat',
  gaffe: 'magic spell',
  ancient: 'haunted',
  'star-studded': 'blood-soaked',
  'remains to be seen': 'will never be known',
  'silver bullet': 'way to kill werewolves',
  'subway system': 'tunnels I found',
  surprising: 'surprising (but not to me)',
  war: 'interplentary war',
  tension: 'sexual tension',
  optimistic: 'dellusional',
  'doctor who': 'the big bang theory',
  'win votes': 'find pokemon',
  'behind the headlines': 'beyond the grave',
  email: 'poem',
  'facebook post': 'poem',
  tweeting: 'singing',
  tweeted: 'sung',
  tweet: 'song',
  'facebook ceo': 'this guy',
  latest: 'final',
  disrupt: 'destroy',
  meeting: 'menage a trois',
  scientists: 'Channing Tatum and his friends',
  "you won't believe": "I'm really sad about",
  'net neutrality': 'mandatory-break-dancing',
  government: 'alien overlord',
  personal: 'sexual',
  spokesperson: 'royal-midget',
  person: 'tiny horse',
  people: 'angry two year olds',
  americans: 'Dungeons and Dragons players',
  american: 'stupid',
  america: "Westeros",
  fcc: 'Puppy Party',
  months: 'minutes',
  'attorney general': 'Judgey-McJudgerson',
  document: 'birthday cake',
  investigative: 'irritating',
  announced: 'did a back-flip while yelling',
  president: 'biggest llama',
  spokesman: 'royal-midget',
  phone: 'pie',
  google: 'Hooli',
  ceo: 'King',
  reportedly: 'surprisingly',
  report: 'facebook comment',
  wanted: 'reeeeeeeeally wanted',
  money: 'twinkie bars',
  republicans: 'child molesters',
  democrats: 'incest-lovers',
  bank: 'waffle house',
  'donald trump': 'a racist ass-hat',
  trump: 'the ass-hat',
  'the white house': "Toby's living room",
  muslim: 'vegan',
  'sexual misconduct': 'pant-pooping',
  'prime minister': 'prime-rib',
  questions: 'provocative questions',
};

const comedyParser = (bodyArray) => {
  const regExMap = new RegExp(Object.keys(comedyMap).join('|'), 'gi');
  return bodyArray.map((string) => {
    return string.replace(regExMap, (matched) => {
      return comedyMap[matched.toLowerCase()];
    });
  });
};

export default comedyParser;
